---
title: "MusMat • Brazilian Journal of Music and Mathematics"
subtitle: "Editorial board"
---

**Editorial Board** <br>
Dr. Carlos Almada | UFRJ <br>
Dr. Daniel Moreira | UFRJ <br>
Dr. Liduino Pitombeira | UFRJ <br>
Dr. Hugo Tremonte de Carvalho | UFRJ <br>
Dr. Carlos Mathias | UFF <br>
Dr. Robert Peck | USA, Louisiana State University <br>
Dr. Julio Herrlein | UFRGS <br>
Dr. José Oliveira Martins | Portugal, Universidade de Coimbra <br>
Dr. Marcos Sampaio | UFBA <br>
Dr. Rodolfo Coelho de Souza | USP <br>

**Advisory Board** <br>
Dr. Arthur Kampela | UNIRIO <br>
Dr. Carlos Volotão | IME <br>
Dr. Charles de Paiva Santana | UNICAMP <br>
Dr. Gabriel Pareyon | Mexico, Universidad de Guadalajara <br>
Dr. Ciro Visconti | Faculdade Santa Marcelina <br>
Dr. Walter Nery | Faculdade Santa Marcelina <br>
Dr. Jean Pierre Briot | CNRS  <br>
Dr. Paulo de Tarso Camargo Cambraia Salles | USP  <br>
Dr. Petrucio Vianna | UFF <br>
Dr. Stefanella Boatto | UFRJ <br>

**Graphic design, copydesk, cover, publishing, and treatment** <br>
MusMat Research Group