---
title: "MusMat • Brazilian Journal of Music and Mathematics"
subtitle: "Policies"
---

<p style="text-align: justify;"><b>DEFINITIONS</b></p>
<p style="text-align: justify;"><b>Manuscript</b><span style="font-weight: 400;">: the first version of the submitted paper.<br>
</span><b>Accepted manuscript</b><span style="font-weight: 400;">: a manuscript that was accepted under reviewing conditions.<br>
</span><b>Final Manuscript </b><span style="font-weight: 400;">(</span><b>camera ready</b><span style="font-weight: 400;">): an accepted manuscript including all reviewers’ </span><span style="font-weight: 400;">recommendations.<br>
</span><b>Published Paper</b><span style="font-weight: 400;">:</span> <span style="font-weight: 400;">final manuscript with an assigned DOI number publicly available on a MusMat Journal issue.<br>
</span><b>Reviewer</b><span style="font-weight: 400;">: a researcher who gives a critical analysis followed by a three-way decision regarding a manuscript sent by the Editor: "accepted", "rejected", or "accepted with conditions".<br>
</span><b>Chief Editor</b><span style="font-weight: 400;">: a person in charge of receiving a manuscript and taking a three-way decision over it: "accept", "reject", or "initiate the double-blind peer-reviewing process". From now on, the Chief Editor will be referred to as Editor.<br>
</span><b>Editorial Board</b><span style="font-weight: 400;">: a group of editors in charge of graphic design, cover, publishing, and treatment of the MusMat issue to be published.<br>
</span><b>Advisory Board</b><span style="font-weight: 400;">: a group of experts in the journal’s field who assist the editorial process upon the requirement of the Editor.</span></p><br>
<p style="text-align: justify;"><b>TERMS OF USE</b></p>
<p style="text-align: justify;"><span style="font-weight: 400;">THESE TERMS OF SERVICE GOVERN THE USE OF THIS WEBSITE MADE AVAILABLE BY MUSMAT RESEARCH GROUP. BY ACCESSING THIS SITE, YOU RATIFY YOUR KNOWLEDGE AND AGREEMENT TO THESE TERMS OF USE. THESE TERMS OF USE MAY BE CHANGED AT ANY TIME WITHOUT NOTICE. AFTER THE IMPLEMENTATION OF SUCH CHANGES THE USE OF THIS SITE CONSTITUTES YOUR KNOWLEDGE AND ACCEPTANCE OF THE CHANGES. PLEASE REFER TO THE TERMS OF USE BEFORE EACH USE TO CHECK FOR POSSIBLE MODIFICATIONS.</span></p>
<p style="text-align: justify;"><b>ACCESS TO THE SITE</b></p>
<p style="text-align: justify;"><span style="font-weight: 400;">To access this site, you do not need to provide details for registration or other information, such as name and email. </span></p>
<p style="text-align: justify;"><b>USAGE RESTRICTIONS</b></p>
<p style="text-align: justify;"><span style="font-weight: 400;">The content of this site must be used for academic purposes expressly permitted by MusMat Research Group. You may not use it for any other purpose, including commercial purposes, without the express and written prior consent of the Group. For example, you may not (and may not authorize third parties) to: a) associate our brand with any other company or; b) make a frame of this site in another. For the purposes of this term of use, "associating the trademark of our Group" means displaying the name, logo, trademark, or other means of attribution or identification at source in such a way that gives the user the impression that such source has the right to display, publish, or distribute this site or its content made available by it. You agree to cooperate with the MusMat to cease any unauthorized association or frame.</span></p>
<p style="text-align: justify;"><b>INFORMATION PROPERTY</b></p>
<p style="text-align: justify;"><span style="font-weight: 400;">The material and content (referred to herein as "content") accessible on this site and any other website owned, licensed or controlled by MusMat Research Group belongs to the Group or the source (authors) that provided the content to our Group, and our Group or the source in question owns all right, title and profit in the Content. Likewise, content may not be copied, distributed, republished, uploaded, posted, or transmitted by any means without the prior written consent of our Group, or unless it is used for non-profit academic purposes. By doing so, you may not remove, alter or cause removal or alteration in any Content. Modification or use of the Content in any form other than those expressly described in this Terms of Use violates the intellectual property rights of our Group. Neither authorship nor intellectual property is transferred to you when accessing this site.</span></p>
<p style="text-align: justify;"><b>HYPERLINKS</b></p>
<p style="text-align: justify;"><span style="font-weight: 400;">This site may contain links to other websites that are not maintained or even related to our Group. Hyperlinks to such websites are provided as a service to users and are not affiliated with this site or our Group. Our Group does not review all or even any of these sites and is not responsible for their content. You take the risk by accessing these hyperlinks and our Group makes no representations or warranties about the fullness or accuracy of the hyperlinks and the websites to which they target them. Finally, completing any hyperlink to a third party site does not necessarily imply endorsement by our Group of that site.</span></p>
<p style="text-align: justify;"><b>LEGAL NOTICE</b></p>
<p style="text-align: justify;"><span style="font-weight: 400;">You understand that our Group cannot and does not warrant that files available for download from the Internet are free of viruses, worms, Trojan horses or other code that may manifest contaminating or destructive properties. You are responsible for implementing sufficient procedures and checkpoints to meet your security requirements and for maintaining means external to this site for rebuilding any lost data. Our Group assumes no responsibility or risk for the use of the Internet.</span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">The Content is not necessarily complete and up-to-date and should not be used to replace any reports, statements or notices given by the Group. Authors, contributors and others must use the Content in the same way as any other educational environment and should not rely solely on the Content to the detriment of their own professional judgment. The information obtained from using this website is not complete and does not cover all questions, topics or facts that may be relevant to your purposes.</span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">THE USE OF THIS SITE IS YOUR SOLE RESPONSIBILITY. THE CONTENT IS OFFERED AS IS AND WITHOUT WARRANTIES OF ANY KIND, EXPRESSED OR IMPLIED. OUR GROUP DOES NOT GUARANTEE THAT THE FUNCTIONS OR CONTENTS PRESENT ON THIS SITE WILL BE CONTINUOUS, ERROR-FREE, THAT FAILURES WILL BE CORRECTED OR THAT THIS SITE AND SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER DESTRUCTIVE COMPONENTS. OUR GROUP DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS RELATED TO THE USE OR RESULTS OF THE USE OF THE CONTENT IN TERMS OF ACCURACY, RELIABILITY OR OTHERWISE. THE CONTENT MAY INCLUDE TECHNICAL INACCURACIES OR TYPOGRAPHICAL ERRORS AND THE GROUP MAY MAKE CHANGES OR IMPROVEMENTS AT ANY TIME. YOU, AND NOT OUR GROUP, ASSUME THE COST OF ANY SERVICE, REPAIR OR CORRECTION NECESSARY IN CASE OF ANY LOSS OR DAMAGE RESULTING FROM THE USE OF THIS SITE OR ITS CONTENTS. OUR GROUP MAKES NO WARRANTY THAT THE USE OF THIS CONTENT WILL NOT INFRINGE THE RIGHT OF ANOTHER AND ASSUMES NO RESPONSIBILITY FOR ERRORS OR OMISSIONS IN SUCH CONTENT.</span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">All information on this site whether historical in nature or forward-looking is valid only for the date that it was posted on the site and the Group undertakes no obligation to update such information after it is published or remove such information from this site if it is not (more) accurate or complete.</span></p>
<p style="text-align: justify;"><b>LIMITATION OF RESPONSABILITY</b></p>
<p style="text-align: justify;"><span style="font-weight: 400;">THE GROUP, ITS AFFILIATES, AUTHORS FROM THE JOURNAL, LICENSORS, SERVICE PROVIDERS, CONTENT PROVIDERS, EDITORIAL BOARD, AND REVIEWERS SHALL NOT BE LIABLE FOR ANY EVENTUAL, DIRECT, INDIRECT, PUNITIVE, REAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY OR ANY OTHER TYPE, INCLUDING LOSS OF INCOME, PAIN AND SUFFERING, EMOTIONAL OR SIMILAR STRESS EVEN IF THE GROUP HAS ADVISED ON THE POSSIBILITY OF SUCH DAMAGES.</span></p>
<p style="text-align: justify;"><b>TRADEMARKS</b></p>
<p style="text-align: justify;"><span style="font-weight: 400;">Trademarks and logos on this site are the property of MusMat Research Group or the party that made them available to the Group. MusMat and the parties that have made the mark available and then own all rights in them.</span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">You may not post send, submit or connect to this site any material that:</span></p>

<ul style="text-align: justify;">
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">You do not have the right to post, including material owned by third parties</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Advocate illegal activity or discuss the intention to do something illegal;</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Contains vulgar, obscene, pornographic, or indecent subjects;</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">May insult others, defame, slander, invade privacy, stalk, be obscene, pornographic, racist, harass or offend;</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Seeks to exploit or harm children by exposing them to inappropriate content, asking about personal information or any other kind;</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Infringes any intellectual property or other right of a person or entity, including copyright, trademark, or publicity rights;</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Violates any law or may be considered to violate the law;</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Impersonates or misrepresents your connection to any entity or person; or manipulates titles or identifiers to cover up the origin of the content</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Promotes any commercial enterprise (e.g. offer products or services on sale) or engage in any way in a commercial activity (e.g. conduct sweepstakes or contests, display sponsor banners and/or solicit goods and services) except as specifically authorized on this site;</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Requests funds, disclosures or sponsors;</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Includes programs with viruses, worms, and/or Trojan horses or any other computer code, file, or program intended to interrupt, destroy, or limit the functionality of any computer or telecommunications software or hardware;</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Interrupts the normal flow of the conversation, make the screen "roll" faster than other users can track or even act in a way that affects other people's ability to engage in real-time activities on this site;</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Includes files in any proprietary format;</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Disobeys any policy or rule established from time to time for the use of this site or any network connected to it; Or</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Contains hyperlinks to sites that contain content that fits the descriptions above.</span></li>
</ul>
<p style="text-align: justify;"><span style="font-weight: 400;">Even without the obligation to do so, our Group reserves the right to monitor the use of this website to determine compliance with this Terms of Use as well as to remove or veto any information for any reason. Either way you are completely responsible for the content of your submissions. You know and agree that neither the Group nor any third party providing content to the Group will assume any responsibility for any action or inaction of the Group or such third party in respect of any submission.</span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">BY ACCEPTING THIS AGREEMENT YOU EXEMPT MUSMAT RESEARCH GROUP FROM ANY CONSEQUENCE RESULTING FROM ANY ACTION OF THE GROUP DURING OR AS A RESULT OF ITS INVESTIGATIONS AND/OR ACTIONS TAKEN RESULTING FROM INVESTIGATIONS OF BOTH THE GROUP AND THE COMPETENT AUTHORITIES OF JUSTICE.</span></p>
<p style="text-align: justify;"><b>BLIND REVIEW</b></p>
<p style="text-align: justify;"><span style="font-weight: 400;">All submissions to MusMat are read blind. To ensure such a reading, please submit your text to the MusMat Editor without making reference to yourself throughout the text (including references). The editor will not consider submissions that might disclose the identity of the author(s).</span></p>
<p style="text-align: justify;"><b>AUTHOR RIGHTS/ATTRIBUTION/USAGE</b></p>
<p style="text-align: justify;"><span style="font-weight: 400;">Authors who publish with this journal agree to the following terms:</span></p>

<ol style="text-align: justify;">
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Authors retain copyright and grant the journal the right of publication and distribution of the published paper, allowing others to share the work with an acknowledgment of the work's authorship and its publication in this journal.</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Authors are responsible for supplying written evidence of copyright permission with respect to the reproduction of musical examples and similar materials (e.g. a figure, diagram, scheme, table, text, etc.). It will expedite the processing of your contribution if any necessary agreements with copyright holders have already been sought when material is submitted to the journal. </span><b>MusMat Journal will not publish the paper without this information</b><span style="font-weight: 400;">.</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Authors are able to share the published paper on other platforms (e.g. academia.edu, arXiv.org, researchgate.net, etc.).</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Authors may review, change, or expand his/her paper to publish in another journal or book provided an acknowledgment of MusMat Journal, if it is in accordance with the copyright terms of the other publisher.</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Authors are fully and legally responsible for the content of their paper.</span></li>
</ol>
<p style="text-align: justify;"><b>POLICY ON CONFLICTS OF INTEREST </b></p>
<p style="text-align: justify;"><span style="font-weight: 400;">To ensure public trust in the peer review process and credibility of articles and reviews published in MusMat journal, all participants (reviewers and editors) agree to disclose any relationships that could be perceived as presenting a conflict of interest. In the case of any such disclosed relationship, arrangements for alternate reviewers and/or editors will generally be made. Alternative arrangements may be waived if it is determined that the participant is in an ideal position to engage in robust and informed scholarly dialogue, and if the participant agrees to act in good faith, minimizing any potential conflict.</span></p>
<p style="text-align: justify;"><strong>PUBLICATION ETHICS AND GOOD PRACTICES</strong></p>
<p style="text-align: justify;"><span style="font-weight: 400;">The ethics and quality of publications are crucial aspects for MusMat journal. Therefore, we require ethical behavior from authors, Editor, and reviewers. We do not accept plagiarism or any other unethical behavior, such as manifestations of racism, homophobia, misogyny, xenophobia, or any other hate speech.</span></p>
<p style="text-align: justify;"><b>DUTIES OF THE EDITOR</b></p>
<p style="text-align: justify;"><span style="font-weight: 400;">The Editor is responsible for publication decisions, which includes defining the articles to be sent to reviewers, considering whether the submitted manuscripts are in accordance with the editorial policies. </span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">The Editor is responsible for all publication decisions, which includes to:</span></p>

<ol style="text-align: justify;">
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Define the articles to be sent to the reviewers;</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Verify whether the submitted articles are in accordance with the editorial policies and by the Editorial Board and Referees;</span></li>
 	<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Intermediate the dialogue between authors and Referees.</span></li>
</ol>
<p style="text-align: justify;"><span style="font-weight: 400;">The editorial policies must observe the legal requirements regarding defamation, copyright infringement, plagiarism, and all items defined in the section ‘Publication Ethics and Good Practices’ above. </span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">Regarding the Editor’s publication decisions, the criteria must not take into consideration aspects such as the race, sex, sexual orientation, religious belief, ethnic origin, nationality or the political philosophy of the authors.</span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">The information about the manuscript and its author is strictly confidential, and, therefore, the Editor and other members of the Editorial Board will not disclose it, except to the reviewers and editorial advisors.</span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">The necessary actions shall be taken by the Editor in the case of ethical complaints regarding a manuscript or published paper.</span></p>
<p style="text-align: justify;"><b>DUTIES OF REVIEWERS</b></p>
<p style="text-align: justify;"><span style="font-weight: 400;">Contribution to editorial decisions</span><span style="font-weight: 400;">: the review provided by the reviewers are aimed to assist the Editor in the final decision regarding the manuscript. The reviewer must have in mind that his/her review will be forwarded to the author.</span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">Punctuality</span><span style="font-weight: 400;">: in order to maintain the schedule of the editorial activities, the reviewer must follow the deadlines established by the Editor. In case he/her does not feel qualified to analyze the manuscript, the Editor must be communicated as soon as possible.</span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">Confidentiality</span><span style="font-weight: 400;">: manuscripts received for review must be considered as confidential documents and must not be discussed with or shown to others.</span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">Objectivity</span><span style="font-weight: 400;">: the reviewers must not take his/her personal opinion on the subject of the manuscript in the review, which should be guided by objective and scientific standards.</span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">Plagiarism and references</span><span style="font-weight: 400;">: any indication of plagiarism must be communicated to the Editor, as well as relevant references not mentioned by the author.</span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">Disclosure and conflict of interest:</span><span style="font-weight: 400;"> information acquired from the manuscript during the reviewing process must not be used by the reviewer for personal gain at the expense of the author’s research and originality. The reviewer should not evaluate manuscripts in which conflicts of interest are identified due to competition, collaboration or other relationships with the authors or institutions linked to the manuscripts. </span></p>
<p style="text-align: justify;"><b>DUTIES OF AUTHORS</b></p>
<p style="text-align: justify;"><span style="font-weight: 400;">General rules:</span><span style="font-weight: 400;"> authors must submit manuscripts that are the result of original research in an objective and clear manner containing all the information necessary for others to replicate and evaluate the research.</span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">Originality and plagiarism: </span><span style="font-weight: 400;">submitted manuscripts should contain entirely original works, and if work and/or texts from other sources are used it must be properly cited. If any indication of plagiarism is noticed, the manuscript will be automatically rejected.</span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">Multiple, redundant and simultaneous publication:</span><span style="font-weight: 400;"> the author must not submit manuscripts containing essentially the same content in more than one journal, annals of conferences and similar publications. </span></p>
<p style="text-align: justify;"><span style="font-weight: 400;">About the sources</span><span style="font-weight: 400;">: important works for the investigation reported in the manuscript should be recognized and properly cited. Private information, correspondence, or discussion with third parties can only be used with permission of the source.</span></p>