---
title: "Vol. I, No. 1 - December 2016"
subtitle: "MusMat • Brazilian Journal of Music and Mathematics"
---

## Full edition
[Download here](../wp-content/uploads/2017/10/MusMat-Journal-1st-issue.pdf)

## Individual papers
### Evolutionary Variation Applied to the Composition of CTG, for Woodwind Trio
**Carlos de Lemos Almada**
<p style="text-align: justify;"><strong>Abstract</strong>: This paper integrates a broad research on musical variation. It specifically addresses an original concept, namely "evolutionary variation" (EV), resulted from an association between Schoenbergian principles of Grundgestalt and developing variation and some ideas from Genetics and Evolutionary Biology. The application of this concept in a compositional system (Gr-S) aims at the production of a large number of variants from a basic musical idea, covering a wide spectrum of similarity relationships. An application of EV in the composition of CTG, for woodwind trio, is described in the second part of the paper.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em>Musical and Biological Evolution. Grundgestalt and Developing Variation. Computer-Aided Composition. </em></p>
[Download paper](../wp-content/uploads/2016/12/01-almada.pdf)

### Teaching Atonal and Beat-Class Theory, Modulo Small
**Richard Cohn**
<p style="text-align: justify;"><strong>Abstract</strong>: The paper advances a pedagogical program that models small cyclic systems before teaching the twelve-element chromatic system of atonal theory. The central properties, relations and protocols of atonal theory (complementation, inclusion, invariance, transpositional equivalence, set classification and labeling, maximal evenness) are introduced in the smallest cyclic system to which they apply. All cyclic systems of 2 to 9 elements have at least one familiar musical application, modeling beat-class (rhythmic) cycle, pentatonic and diatonic scales. By the time students have scaled up to a twelve-element universe, they are technically prepared to explore it, and to appreciate its special properties. Along the way, they have learned a model of meter, an otherwise under-theorized aspect of music pedagogy.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em>Atonality. Musical set theory. Time cycles.</em></p>
[Download paper](../wp-content/uploads/2016/12/02-cohn.pdf)

### Sound Shizuku Composition: a Computer-Aided Composition System for Extended Music Techniques
**Ivan Eiji Simurra and Jônatas Manzolli**
<p style="text-align: justify;"><strong>Abstract</strong>: We discuss in this paper a new environment for computer aid musical composition which is designed to create works centered on the creative use of instrumental extended techniques. The process is anchored on computational techniques to retrieve musical information via audio descriptors. We developed an analytical process, based on the extraction of spectral characteristics of a Sound DataBase (SDB), and on supporting the compositional planning as follows: relate statistical measures to the spectral behavior ofspecific execution modes of various instruments contained in the SDB. The result of the process is a palette of possibilities that assists the composer decisions regarding to the desired orchestration to be applied in a musical piece. The paper presents then the motivation and context to develop the environment, describes and characterizes the audio descriptors that have been studied, presents the computer system architecture and discusses the results obtained with Sound Shizuku.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Composition. Computer-Aided Orchestration. Audio Descriptors. Extended Techniques. Interdisciplinary Music Computation. </em>></p>
[Download paper](../wp-content/uploads/2016/12/03-manzolli.pdf)

### Music as a Carbon Language: A Mathematical Analogy and its Interpretation in Biomusicology
**Gabriel Pareyon**
<p style="text-align: justify;"><strong>Abstract</strong>: Carbon dynamics influence human physiology, culture and social patterns. Along centuries, linguists had been sufficiently discussed how breathing and cardiovascular performance set preconditions for word segmentation, phrasing, repetition, iteration, variation and expressiveness. Less attention had been paid to this influence as reflected in music, due to the belief that music can be “purely instrumental”, and therefore far away from speech. However music, dance, respiration and verbal language share common evolutionary grounds, as well as important physiological features and constraints related to the organic properties of carbon and to its role in biological evolution. In this context, this contribution interprets chemical proportions in bioorganic compounds as analogies of their musical parallels, with consequences to music theory. Mathematical evidence is suggested for sketching a carbon hypothesis of music. From this perspective, music is more a feature and a consequence of chemical and biological constraints (not exclusive of humans), than a product “purely social” or “uniquely cultural”.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Carbon. 1/f Noise. Zipf. Music Language Self-similarity. </em></p>
[Download paper](../wp-content/uploads/2016/12/04-pareyon-v10.pdf)

### All-(Generalized-)Interval(-System)Chords
**Robert W. Peck**
<p style="text-align: justify;"><strong>Abstract</strong>: We survey the all-interval chords of small order and the interval systems in which they are situated. We begin with an examination of traditional all-interval chords in chromatic pitch-class spaces, and extend the notion of their structure to their counterparts in David Lewin’s Generalized Interval Systems. Mathematically, we observe that these chords belong to three categories of difference sets from the field of combinatorics: (v, k, 1) planar difference sets, (v, k, 2) non-planar difference sets, and (v, k, 1, t) almost difference sets. Further, we explore sets of all-interval chords in group-theoretical terms, where such sets are obtained as orbits under the action of the normalizer of the interval group. This inquiry leads to a catalog of the 11,438 all-interval chords of order k, where 2 6 k 6 8. We conclude with remarks about future work and open questions.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> All-interval Chords. Generalized Interval Systems. Group Theory. Difference Sets. </em></p>
[Download paper](../wp-content/uploads/2016/12/05-peck.pdf)

### On the Relation of Quality and Quantity in the Context of Musical Composition
**Alexandre Reche e Silva**
<p style="text-align: justify;"><strong>Abstract</strong>: With this paper we aim to highlight the connection between quality and quantity, from a musical point of view. For this, we heuristically sketch a typology of musical qualities. Every quality offers a gamut of gradations. Each degree inside this range can be indexed as a value, making a range of quantities available. The changes of a musical quantity over time is represented as a list of values. This list can be manipulated through a variety of mathematical operations. Such approach can be applied to any musical quality (thus, encouraging students to face the elements assembled in a composition from the start). Some of these operations are presented here as functionalities of J-Syncker, an assistant software for the generation of pre-compositional material.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Music Composition. Musical Qualities. Musical Quantities. Lists. J-Syncker </em></p>
[Download paper](../wp-content/uploads/2017/10/Reche.pdf)

### Contour Algorithms Review
**Marcos da Silva Sampaio and Pedro Kröger**
<p style="text-align: justify;"><strong>Abstract</strong>: In this paper, we present some problems of two Music Contour Relations Theory operations algorithms: the Refinement of Contour Reduction Algorithm, which was developed by Rob Schultz, and the Equivalence Contour Class Prime Form algorithm, which was developed by Elizabeth Marvin and Paul Laprade. We also propose two alternative algorithms to solve these problems.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Music Contour Theory. Reduction Algorithm. Algorithm. Equivalent contour classes.  </em></p>
[Download paper](../wp-content/uploads/2016/12/07-sampaio.pdf)

### Discrete and Combinatorial Mathematics, Geometry and Mathematics of Continuous Functions Used in Some of my Compositional Projects
**Rodolfo Coelho de Souza**
<p style="text-align: justify;"><strong>Abstract</strong>: This paper intends to demonstrate the different ways many of my compositional projects used mathematical tools, from the pre-compositional stage through a final product done with sound synthesis. These tools are of diverse nature, depending on the theoretical needs of the problem faced. In some cases, the project employed discrete and combinatorial mathematics. In other cases, geometry was a useful tool to visualize rhythmic  anipulations. Irrational numbers were the basis of a non-conventional tuning proposition. Continuous functions, like “sine”, are at the core of digital sound synthesis and, in a particular project, served to the design of a digital filter.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Algorithmic composition. Inharmonic tuning. Fractal diminution. Set similarity. Cyclic rhythm. Digital filter. </em></p>
[Download paper](../wp-content/uploads/2016/12/08-souza_artigo_v08.pdf)