---
title: "Vol. II, No. 2 - December 2018"
subtitle: "MusMat • Brazilian Journal of Music and Mathematics"
---

## Full edition
[Download here](../wp-content/uploads/2018/12/MusMat_Journal_V2_N2.pdf)

## Individual papers
### The State of the Art: New Directions in Music and Mathematics
**Robert Peck**
<p style="text-align: justify;"><strong>Abstract</strong>: This article is adapted from the author’s 2018 keynote lecture at the Third National Congress of Music and Mathematics in Rio de Janeiro. It discusses the history of the fields of mathematical and computational musicology, as well as the formation of the Journal of Mathematics and Music, which the author co-founded in 2007. Further, it identifies recent trends in the fields of mathematical and computational musicology through an examination of the journal’s special issues.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Mathematical Musicology. Computational Musicology. </em></p>
[Download paper](../wp-content/uploads/2018/12/05-peck-lecture.pdf)

### Axis of Contextual Inversion
**Ciro Visconti**
<p style="text-align: justify;"><strong>Abstract</strong>: Contextual inversion operations are commonly associated with neo-Riemannian transformations, but the labels P, L and R and their obverse versions P’, L’ and R’ only map sets with at least one common pitch-class. This article shows how contextual inversion operations can be mapped by axes in a similar manner to In-operations, and how the positions of these axes can also be labeled. The advantage of this approach is that it will make the representation of any contextual inversion operation between members
of any set class possible, which will be useful for both musical analysis and pre-compositional processes. The theoretical concepts developed in this article will be demonstrated in analyses of passages of works by Webern, Stravinsky and Villa-Lobos.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Contextual inversion. Neo-Riemannian Theory. Graph Theory. Voice-leading. </em></p>
[Download paper](../wp-content/uploads/2018/12/06-axis-of-contextual-inversion.pdf)

### A Systemic Model for Debussy's Prélude No.1
**Liduino Pitombeira**
<p style="text-align: justify;"><strong>Abstract</strong>: This paper examines the analytical-compositional methodology called Systemic Modeling, proposed by Pitombeira as an intertextual tool that grasps deep parametric relationships within musical works. A discussion of the Theory of Compositional Systems and the Theory of Intertextuality, with examples, is provided in order to pave the way to the understanding of Systemic Modeling. Short examples of systemic modeling are given for clarification of its methodological phases. The entire Prélude No.1, by Claude Debussy, is modeled and a new piece is composed from this systemic model.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Systemic Modeling. Compositional Systems. Parametric Generalization. Intertextuality. Claude Debussy. </em></p>
[Download paper](../wp-content/uploads/2018/12/07-a-systemic-model-for-debussys-prelude-no.1.pdf)

### Contour Similarity Algorithms
**Marcos da Silva Sampaio**
<p style="text-align: justify;"><strong>Abstract</strong>: The Musical Contour literature provides multiple algorithms for melodic contour similarity. However, most of them are limited in use by the melody length of input data. In this paper I review these algorithms, propose two new algorithms, compare them in three experiments with contours from the Bach Chorales, from a Schumann song and automated generated, and present a brief review of the contour and similarity literature. </p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Music Contour Theory. Melodic Similarity. Algorithms. Music Analysis. Computational Musicology. </em></p>
[Download paper](../wp-content/uploads/2018/12/08-contour-similarity-algorithm.pdf)

### Z-Related Hexachords explained by Transpositional Combination and the Complement Union Property
**Robert Morris**
<p style="text-align: justify;"><strong>Abstract</strong>: Two pcsets that have the same interval-class vector (ICV) but are not related by transposition (Tn) and/or Inversion (I) are said to be Z-related. The Z-relation can be extended to pairs of setclasses; the members of the two set-classes have the same ICV, but the members of one are not related to the other under Tn or TnI. This paper shows how the 15 Z-related hexachordal setclasses can be explained by two functions on pcsets: 1) A hexachord can be described as the transpositional combination of two smaller sets; 2) A hexachord can be described as the complement union of two smaller pcsets. The 15 hexachordal pairs can be constructed by using one or more of five combinations of these two functions. For instance, the set-classes 6-10 [013457] and 6-39 [023458] are constructed by the transpositional combination of two [013] sets at the major 3rd and the complement union of a [048] trichord (augmented chord) and a [013] set.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Atonal Set-theory. Z-relation. Transpositional Combination. Complement Union. Holomorphic Sets. Twelve-tone Theory. Serial Theory. </em></p>
[Download paper](../wp-content/uploads/2019/01/09-z-related-hexachords.pdf)