---
title: "Vol. II, No. 1 - May 2018"
subtitle: "MusMat • Brazilian Journal of Music and Mathematics"
---

## Full edition
[Download here](../wp-content/uploads/2018/06/MusMat-Journal-Vol.-2-1.pdf)

## Individual papers
### Cycles in Music: Spaces, Experience and Applications in Music Theory and Composition
**Guilherme Bertissolo**
<p style="text-align: justify;"><strong>Abstract</strong>: This paper focuses the idea of cycle and its approaches in music theory, in order to propose further application to music composition. The impulse for reseaching cycle was made possible through a previous research, in which I proposed a conceptual framework for the relationship between music and movement in Capoeira. Here, I first discuss the idea of cycle, then its theoretical approaches, and finally, some compositional processes based on cycles.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Cycle, composition. Creative Process. Composition.  </em></p>
[Download paper](../wp-content/uploads/2018/06/01-Bertissolo-1.pdf)

### Rudiments of Simulation-Based Computer-Assisted Analysis Including a Demonstration With Steve Reich’s Clapping Music
**Charles de Paiva**
<p style="text-align: justify;"><strong>Abstract</strong>: Based on previous experiments the article presents the most basic principles of a computational approach for musical analysis that through deterministic algorithms aims to reconstruct and then simulate neighboring variants (called instances) of existing musical scores. For that, adequate numerical representations are required, and their use in Computer-Aided Composition (CAC) systems are presented. Numerical sequences mapping to musical elements such as pitches, durations, and articulations may be computed or hardcoded for subsequent transformation, concatenation, and superimposition. They allow the reconstruction of the segments of a given musical score. The rhythmic pattern of Clapping Music can be modeled as a group of beats being progressively deprived of one beat, each group being separated by a rest, and the sequence concatenated with its retrograde. The sequence is subsequently transformed by the successive application of “phase shifts”. A graphical interpretation of the piece is introduced using barcodes. Variations are envisaged by manipulating parameter values, each different value corresponding to a specific instance. Usually, parameters reflect compositional choices, but completely arbitrary models are possible. Such is the case of an alternative model of Clapping Music where a number is converted to binary representation and then mapped to rests and beats of eighth-notes. The manipulation of strong parameters modifies structural features of the musical score while weak parameters may only change the way the score is notated. The set of possible simulations gives rise to a space of nstances. It can be analyzed through diachronic analysis, where a small group of variations is compared to the original piece, or achronic analysis, where variations are seen as single points in the space.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Algorithmic composition. Computer-assisted Musical Analysis. Computational Musicology. Steve Reich. </em></p>
[Download paper](../wp-content/uploads/2018/06/02-Charles-1.pdf)

### Cosmicizing Sound music – cosmos – number
**Luigi Irlandini**
<p style="text-align: justify;"><strong>Abstract</strong>: The compositional practice to be described in this article includes number and proportion as decisive factors for the problem of musical form. The role of number and proportion in my music is entirely dependent on the idea of music composition as cosmology, which has two aspects: the “scientific”, in which musical form is determined by formative principles or techniques, and the “contemplative”, which confers to the music an iconic relationship with mystical or mythic cosmologies such as those of the Pythagoreans and of ancient India Vedas and Vedanta. To better understand the context in which number and proportion relate to musical form in some of my works, I will first develop the ideas of composition as cosmology, composition as cosmogony, and spiral time. After this, I will briefly study the role of proportion in the temporal organization of a few key works, and conclude with some other general considerations concerning number and proportion in contemporary music. The idea of “cosmicizing sound” will surface naturally from the considerations about the poetics and aesthetics of my music.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Compositional Processes. Formative Principles. Cosmology. Number and Music. Cosmology and Music. </em></p>
[Download paper](../wp-content/uploads/2018/06/03-Luigi-1.pdf)

### A Study of Variation in Temporal Structure of Sonata Form
**Luka Marohnic**
<p style="text-align: justify;"><strong>Abstract</strong>: In this paper it is shown that the concept of the Eighteenth-Century Sonata form, under certain conditions, implies exact constraints to its temporal structure, which are essential to keep its inner proportions balanced. The plastic number of Hans van der Laan appears to be closely related to the concordance of lengths of the vital parts of a sonata-form movement of type 3 on Hepokoski and Darcy scale. Furthermore, a probabilistic model of basic variation in the structure of such movement is developed from scratch and empirically justified by analyzing instrumental works of Wolfgang Amadeus Mozart.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Sonata form. Perception. Plastic number. Morphic number. Lognormal distribution. </em></p>
[Download paper](../wp-content/uploads/2018/06/04-Luka-1.pdf)

### Nesting and Intersections between Partitional Complexes
**Pauxy Gentil-Nunes**
<p style="text-align: justify;"><strong>Abstract</strong>: The formalization of musical texture is the main objective of Partitional Analysis. Each integer partition corresponds to a specific textural configuration and is used as a tool to organize and systematize the work with textures through the compositional process. Partitional complexes, on the other hand, are sets of partitions, observed in the analysis of musical excerpts, that work in tune to create stable temporal domains where a referential partition projects, extends or presents itself as dominant. The number of partitions and complexes for a certain instrumental, vocal or electronic medium is finite and implies nestings and intersections that can provide important information about textural possibilities available to the composer. In the present work, the relationships established between distinct artitional complexes are discussed, as well as the characterization of an hierarchy related to the number of total choices that each complex offers to the composer.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Partitional Analysis. Partitional Complexes. Musical Texture. Musical Analysis. Theory of Integer Partitions. </em></p>
[Download paper](../wp-content/uploads/2018/06/09-Pauxy.pdf)

### Iterable Voice-Leading Schemas
**Dmitri Tymoczko**
<p style="text-align: justify;"><strong>Abstract</strong>: An iterable voice-leading schema combines a voice leading with a permutation that determines how the voice leading is to be reapplied. These structures model a wide range of repeating musical patterns from the Renaissance to the resent day.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Voice leading. Sequence. Round. Counterpoint. Orbifold. Geometry. </em></p>
[Download paper](../LINK)

### The Function of Orchestration in Serial Music: The Case of Webern's Variations Op. 30 and a Proposal of Theoretical Analysis
**Didier Guigue**
<p style="text-align: justify;"><strong>Abstract</strong>: Webern’s Variationen op. 30 constituted a well-known milestone in the consolidation of serialism as a compositional technique. It has been the target of a large number of investigations focused on the way the composer developed a broader concept. As could it not be otherwise, his orchestral design is also closely tied to his structural concerns. However, it appears to lack a systematization of the composer’s orchestration principles. Thus, to propose an analysis of Webern’s orchestration, one need to elaborate an ad hoc method, virtually starting from scratch. This paper aims to describe the main points of this method in its current experimental stage. At the same time, we point to some conclusions about Webern’s orchestration according to his aesthetics.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> 20th Century musicology. Webern. Variations op. 30. Textural analysis. Analysis of orchestration. </em></p>
[Download paper](../wp-content/uploads/2018/06/07-Didier.pdf)