---
title: "Vol. III, No. 1 - June 2019"
subtitle: "MusMat • Brazilian Journal of Music and Mathematics"
---

## Full edition
[Download here](../wp-content/uploads/2019/07/MusMat%E2%80%93Brazilian-Journal-of-Music-and-Mathematics-Vol-III-No-1.pdf)

## Individual papers
### Machine Representation of Fundamental Musical Functions
**Marianthi Bozabalidou**
<p style="text-align: justify;"><strong>Abstract</strong>: We consider a sequential machine model with output a cancellative monoid in order to describe fundamental music functions (transposition, inversion, retrogate, change of durations, pitch class distribution, move function). The minimal such machine of a prefix preserving function is provided. Musical functions are classified according the complexity of the minimal sequential transducers representing them. Functions coming from contour situations are shown to be sequential and their minimal machines are constructed. A machine simulation based hierarchy of musical contours and the corresponding classification of musical languages are exhibited.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Musical morphism. Musical Contour. Hierarchy of Musical Objects. Sequential Transducer. </em></p>
[Download paper](../wp-content/uploads/2019/06/05-Bozapolidou.pdf)

### Musical Time: A Gestural Construction
**Guerino Mazzola**
<p style="text-align: justify;"><strong>Abstract</strong>: We propose a mathematical construction of musical time, which is derived from mathematical gesture theory and its application to free jazz. The mathematical construction makes usage of the projective limit of diagrams of gestures.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Musical Time. Gesture Theory. Improvisation. Performance. </em></p>
[Download paper](../wp-content/uploads/2019/06/06-Mazola.pdf)

### Composing with Textures: A Proposal For Formalization of Textural Spaces
**Daniel Moreira de Sousa**
<p style="text-align: justify;"><strong>Abstract</strong>: This paper presents the networks of textures called textural spaces. Each textural space provides not only various ways of encoding the organization of the component parts of a texture, but also the quality of their relations. The textural class space is the most generic description of a texture as it divides the components into two abstract structures: line and block. This basic components are defined by the quality of their appearance and functionality, determined by the uniqueness versus multiplicity of the sounding components therein. The second textural space, called ordered partition space, consist of ascribing an integer partition to specify the number of components within a textural class. Finally, the partition layout space provides the most refined description of a texture among all textural space since it considers the internal order of the components according to their registral placement or timbre distribution. After presenting the various concepts and operations, the paper concludes with a discussion about the potential creative application of them, and how they can be decoded into a musical score.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Musical Texture. Textural spaces. Music Composition. Music Analysis. Theory of Integer Partitions. </em></p>
[Download paper](../wp-content/uploads/2019/07/07-Moreira.pdf)

### Computational Implementation of Henry Pousseur’s Harmonic Networks Applied to Live-electronic Music
**Rael Bertarelli Gimenes Toffolo**
<p style="text-align: justify;"><strong>Abstract</strong>: Considering the recent discussion involving the improvisational techniques and the more speculative structural process in the creation of live electronic music, we present, in this paper, the computational implementation of Pousseur’s Harmonic Network in SuperCollider computer language in order to contribute to the development of real-time music. Initially, we present a brief review of the Pousseurian Harmonic thinking and how the Belgian composer created Harmonic Networks, discussing their uses for music making. Then, we present how Pousseur’s Harmonic Network was implemented in SuperCollider computer language considering the algorithmic solutions to this task. Finally, we demonstrate how Harmonic Networks can be used in live electronics compositions.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Pousseur’s Harmonic Network. Live-electronics. SuperCollider. </em></p>
[Download paper](../wp-content/uploads/2019/07/08-Toffolo.pdf)

### A few more Thoughts about Leibniz: The Prediction of Harmonic Distance in Harmonic Space
**Michael Winter**
<p style="text-align: justify;"><strong>Abstract</strong>: This paper shows how, over 300 years ago, Gottfried Wilhelm Leibniz envisioned James Tenney’s theory of harmonic distance in harmonic space. A description of Tenney’s theory is followed by an analysis of musical ideas contained in letters from Leibniz to Christian Henfling. The analysis compares and contrast Leibniz’s ideas to Tenney’s ultimately showing that they are practically identical.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em>  Gottfried Wilhelm Leibniz. James Tenney. Harmonic Distance. Harmonic Space. Complexity. </em></p>
[Download paper](../wp-content/uploads/2019/06/09-Winter.pdf)