---
title: "Vol. IV, No. 1 - June 2020"
subtitle: "MusMat • Brazilian Journal of Music and Mathematics"
---

## Full edition
[Download here](../wp-content/uploads/2020/06/MusmatV4N1.pdf)

[Errata](../wp-content/uploads/2021/04/Errata_v4n1.pdf)

## Individual papers
### Common Rhythm as Discrete Derivative of Its Common-Time Meter
**Scott Murphy**
<p style="text-align: justify;"><strong>Abstract</strong>: Musicians recognize two important functions over the sixteen points in time, or beat classes, distributed evenly over a common-time measure: metric weight and onset frequency. Existing scholarship acknowledges that these functions are similar but not identical, and researchers tend toward one or the other as a model for metric entrainment. However, if the discrete metric-weight function is converted into a continuous curve, then the two functions strongly correlate: the ordering of each beat class by its backwards discrete derivative on this curve perfectly matches the ordering of each beat class by its onset frequency in a classical corpus.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Rhythm. Meter. Calculus. Conducting. Fourier. </em></p>
[Download paper](../wp-content/uploads/2020/06/05-Scott.pdf)

### Compress to Create
**Jean-Pierre Briot**
<p style="text-align: justify;"><strong>Abstract</strong>: The current tsunami of deep learning has already conquered new areas, such as the generation of creative content (images, music, text). The motivation is in using the capacity of modern deep learning architectures and associated training and generation techniques to automatically learn styles from arbitrary corpora and then to generate samples from the estimated distribution, with some degree of control over the generation. In this article, we analyze the use of autoencoder architectures and how their ability for compressing information turns out to be an interesting source for generation of music. Autoencoders are good at representation learning, that is at extracting a compressed and abstract representation (a set of latent variables) common to the set of training examples. By choosing various instances of this abstract representation (i.e., by sampling the latent variables), we may efficiently generate various instances within the style which has been learned. Furthermore, we may use various approaches for controlling the generation, such as interpolation, attribute vector arithmetics, recursion, and objective optimization, as will be illustrated by various examples. Before concluding the article, we will discuss some limitations of autoencoders, introduce the concept of variational autoencoders, and briefly compare their respective merits and limitations for generating music.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Deep learning. Autoencoder. Latent variables. Music generation. Control. </em></p>
[Download paper](../wp-content/uploads/2020/06/06-Briot.pdf)

### Compositional Systems: Overview and Applications
**Liduino Pitombeira**
<p style="text-align: justify;"><strong>Abstract</strong>: In this paper the theory of compositional systems is described in detail, taking as a starting point the theoretical framework inherent to systems science. The origins of this science and the definitions of its fundamental concepts are provided in the first part of the article, illustrated with musical examples. The central part of the article contains the definition of the concept of compositional system, its typology, and a series of tools that are useful for implementations. Finally, the design of three types of systems (open, semi-open and feedback) are carried out in order to produce small illustrative musical fragments.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Compositional Systems. Systems Science. Systemic Modeling. Probability. </em></p>
[Download paper](../wp-content/uploads/2020/06/07-Pitombeira.pdf)

### Rhythm and Entropy: The Exile of the Metric in the Dance of Pulsation
**Arthur Kampela**
<p style="text-align: justify;"><strong>Abstract</strong>: This essay intends to demonstrate that the very system that codified the rhythmic subdivision subsumed to the metronome’s beat or pulse might offer, through its own mechanisms, a window to its deconstruction and yet, to a new, intrinsic, development. When metric subdivisions occur that are fartheraway from the metronomic beat’s referential, (as when rhythmic deviations by many sub-ratios accumulate underneath a certain rhythmic figure), the performer experiences a cognitive loss in the sense of immediate metronomic adjacency. New ways to perform a certain rhythmic outcome buried within the grounds of complex subdivisions require mechanisms to momentarily suspend the main, overarching, beat, to impose emergent, micro-metronomes. These devices are codifiers of speeds whose regularity opens up terrain for new, rhythmical deviations and sub-ratios. They also allow the performer to negotiate between rhythms that present diverging metric configurations, linking their speeds, through rhythmic bridges. As the performer reaches these bridges, located at a deeper level of rhythmic subdivision, he/she ought to return to the main metronomic surface using the speed managed within these momentary micro-metronomes. Such performative and cognitive inversion, lies at the center of the Micro-Metric Modulation Theory.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Micro-Metric Modulation. Ratios and Sub-ratios. Complex Rhythms. Micro Metronomes. Diverging Metric Configurations. Commutative and Associative Properties of Rhythm. </em></p>
[Download paper](../wp-content/uploads/2020/06/08-Kampela.pdf)

### Scales, Counterpoint Triples and their Groups
**Marianthi Bozabalidou**
<p style="text-align: justify;"><strong>Abstract</strong>: General scale systems are defined to be linearly ordered finite sets of musical objects. Apart from the common pitch scales we may also speak of duration and interval scales, major and minor scale schemes, ancient greek trope scale schemes. The fundamental groups of a scale (clock group and group of rows) are discussed. The principal counterpoint triple of a scale Σ consists of the operators RΣ (Σ-retrograde), TΣ (Σ-transposition) and IΣ (Σ-inversion). The group they generate will be referred to as a counterpoint group of Σ. A wide class of counterpoint triples is presented extending the composition material of n-tone music. Variations of twelve-tone pieces may be derived by applying these triples. Counterpoint spaces (CP-spaces) are reachable left actions of counterpoint groups. Such an action is actually simply transitive. Major and minor chords are defined with respect to a pair (p,q) of natural numbers playing the role of major and minor thirds respectively. It is shown that (p,q)-consonant chords in a CP-space constitute a CP-space as well.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Scale. Clock and Row Groups of a Scale. Counterpoint Groups. Counterpoint Spaces. </em></p>
[Download paper](../wp-content/uploads/2020/06/09-Bozabalidou.pdf)