---
title: "Vol. IV, No. 2 - December 2020"
subtitle: "MusMat • Brazilian Journal of Music and Mathematics"
---

## Full edition
[Download here](../wp-content/uploads/2020/12/MusmatV4N2.pdf)

[Errata](../wp-content/uploads/2021/03/ERRATA.pdf)

## Individual papers
### Partitional Harmony: The Partitioning of Pitch Spaces
**Marcos Feitosa**
<p style="text-align: justify;"><strong>Abstract</strong>: In this preliminary work, we seek to present a brief historical review of the use of partitions in music, to provide a concise introduction to the theory of partitions, and lastly, through an extensive bibliographic revision and a thoughtful theoretical reflection, to lay the foundations of what we call partitional harmony – a comprehensive harmonic conception which relates the theory of partitions to several fields of post-tonal music theory. At the end, some basic operations (pitch, transposition, inversion, and multiplication) are defined and an illustrative musical application is provided, followed by our research prospects.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Post-Tonal Music Theory. Pitch-Class Set Theory. Pitch Spaces. Theory of Partitions. Partitional Harmony. </em></p>
[Download paper](../wp-content/uploads/2020/12/Feitosa.pdf)

### Aspects of Performance Practice in Morton Feldman's Last Pieces
**Robert Morris**
<p style="text-align: justify;"><strong>Abstract</strong>: Morton Feldman’s *Last Pieces* for piano solo of 1959 poses an interesting interpretive problem for the performer. As in many Feldman compositions of the 1950s and 60s, the first movement of the work is notated as a series of “sound events” to be played by the performer choosing the durations for each event. The only tempo indications are “Slow. Soft. Durations are free.” This situation is complicated by Feldman’s remark about a similar work from 1960, “[I chose] intervals that seemed to erase or cancel out each sound as soon as we hear the next.” I interpret this intension to keep the piece fresh and appealing from sound to sound. So, how the pianist supposed to play Last Pieces in order to supplement the composers desire for a sound to “cancel out” preceding sounds? To answer this question, I propose a way of assessing the salience of each sound event in the first movement of Last Pieces, using various means of associating each of its 43 sound events according chord spacing, register, center pitch and bandwidth, pitch intervals, pitch-classes, set-class, and figured bass. From this data, one has an idea about how to perform the work to minimize similarity relations between adjacent pairs of sound events so that they can have the cancelling effect the composer desired. As a secondary result of this analysis, many cohesive compositional relations come to light even if the work was composed “intuitively”.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Morton Feldman. Musical Set Theory Analysis. Performance of Twentieth-Century Music. Musical Contour Analysis. </em></p>
[Download paper](../wp-content/uploads/2020/12/Morris.pdf)

### Philosophical Sketches on Category Theory Applied to Music-Mathematical Polar Semiotics
**Gabriel Pareyon**
<p style="text-align: justify;"><strong>Abstract</strong>: This is an attempt to combine Matthai philosophy (of Heraclitan inspiration) and Category Theory using the Yoneda Lemma as a means for harmonizing the traditionally opposite values and conceptions dissociated between the Euclidean tradition and Heraclitus thought. The text is divided in three sections: general background and description of Yoneda, a contextualization on Heraclitan aesthetics and polar semiotics (a notion firstly intuited by I. M. Lotman and Th. Sebeok), and an experiment suggested for the revision of the grounds of music theory, with the purpose of conciliate extremely dissociated notions of music (Euclidean vs. Heraclitan) however making part of a common musical experience and knowledge. Conclusions are addressed to hypothesize that Yoneda lemma may support a robust philosophy of music within the field of Category Theory where any group is isomorphic to a subgroup of a permutation, with one-to-one paired correspondences.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Yoneda embedding. Matthai postulate. Category theory. Polar semiotics. </em></p>
[Download paper](../wp-content/uploads/2020/12/Pareyon.pdf)

### Time and Reversal in Birtwistle's Punch and Judy
**Robert W. Peck**
<p style="text-align: justify;"><strong>Abstract</strong>: We examine the occurrence of peripeteia in Harrison Birtwistle’s 1967 opera Punch and Judy, as manifest in a reversal of cyclic time. Specifically, we extend a metaphorical association between the passage of cyclic time in the opera and discrete rotation in the complex plane generated by the imaginary unit i. Such a rotation moves alternately between the real and the imaginary axes, as scenes in the opera pass correspondingly through sacred and profane orientations. The instance of peripeteia results in a counter rotation, a dramaturgical inversion. To bring this reversal into the metaphor, we extend it from its situation in the complex plane to one in the space of Hamilton’s quaternions, wherein such negation is obtained through the product of upper-level imaginary units.  The scene that contains the reversal and that which consists of the opera’s comic resolution epitomize the drama and occupy the highest level of dramatic structure.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Birtwistle. Inversion. Peripeteia. Complex numbers. Quaternions. </em></p>
[Download paper](../wp-content/uploads/2020/12/Peck.pdf)

### Voice Leading Among Pitch-Class Sets: Revisiting Allen Forte’s Genera
**Paulo de Tarso Salles**
<p style="text-align: justify;"><strong>Abstract</strong>: The theory of PC-set class genera by Allen Forte was an important contribution to the understanding of similarity relations among PC sets within the tempered system. The growing interaction between the universes of PC-sets and transformational theories has been explored the space between sets of the same or distinct cardinality, by means of voice-leading procedures. This paper intends to demonstrate Forte’s method along with proposals by other authors like Morris, Parks, Straus, Cohn, and Coelho de Souza. Some analysis demonstrates such operations in passages picked from Heitor Villa-Lobos’s works, like the Seventh String Quartet and the First Symphony.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Genera. Voice leading. Similarity. Cardinality. Villa-Lobos. </em></p>
[Download paper](../wp-content/uploads/2020/12/Salles.pdf)

### Reading Textural Functions, Instrumental Techniques, and Space Through Partition Complexes
**Pauxy Gentil-Nunes**
<p style="text-align: justify;"><strong>Abstract</strong>: Partitional complexes are sets of discrete textural configurations (called shortly of partitions in Partition Analysis) that successfully interact to construct a global textural structure. This textural mode is called the Textural Proposal of a piece, where referential partitions (those that represent the main features of textural configurations in the excerpt) stand out. This conceptual environment, developed in musical texture formalization through observation and musical repertoire analysis, is now applied to musical practice. In the present work, we highlight three of these situations. The first one deals with the creative flow (compositional process) and its relation with textural planning. The second observes how these same textural functions condition the body’s physical coupling to the instrument (fingers, hands, pedals, instrumentation). Finally, just as an introduction, we envisage some spatial relations, involving instrument distribution on stage, emphasizing historical concert music.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Texture. Partitional Analysis. Textural Design. Performative Partitioning. Partitional Complex. </em></p>
[Download paper](../wp-content/uploads/2020/12/Gentil-Nunes.pdf)