---
title: "Vol. V, No. 1 - June 2021"
subtitle: "MusMat • Brazilian Journal of Music and Mathematics"
---

## Full edition
[Download here](../wwp-content/uploads/2021/06/MusMat_V5_N1.pdf)

## Individual papers
### Beat-Class Set Classes and the Power Group Enumeration Theorem
**Robert W. Peck**
<p style="text-align: justify;"><strong>Abstract</strong>: The theory of beat-class sets originates in the work of Milton Babbitt, who demonstrates a correspondence between modular pitch-class spaces and metric spaces in the framework of total serialism. Later authors, particularly Richard Cohn, John Roeder, and Robert Morris, apply similar concepts to a variety of analytical situations, drawing on concepts and procedures from pitch-class set theory. In light of the correspondence between these theories, the universe of beat-class sets for a given modulus may be partitioned into equivalence classes similar to pitch-class set classes. This study investigates processes of enumerating these equivalence classes. We consider extensions to the theory of beat-class sets by including rhythms with more than one voice. Speciﬁcally, we examine equivalence classes of multiple-voiced beat-class sets using the Power Group Enumeration Theorem (PGET) of Frank Harary and Edgar M. Palmer. The PGET allows us to determine the numbers of equivalence classes of beat-class sets as determined by various groups of transformations: metric shift, retrogradation, and voice permutation, among others. Our results have implications for further applications in pitch-class set theory, serial theory, and transformational theory.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Beat-class set. Equivalence class. Combinatorics. Enumeration. Power group. </em></p>
[Download paper](../wp-content/uploads/2021/06/04-V5n1-Peck.pdf)

### Musical Quasigroups
**Gideon Okon Effiong**
<p style="text-align: justify;"><strong>Abstract</strong>: A musical quasigroup is a musical groupoid in which all its left and right translation mappings are permutations. Some quasigroups of chords with a left (right, middle) identity element have been investigated. It is noted that the left (right, middle) identity element of a musical quasigroup is often associated with the root note of a musical chord. It is shown that chord inversions can be displayed by quasigroups. Examples of musical sequence of triads are constructed by using quasigroups. It is shown that a twelve-tone matrix can be created by using a quasigroup. Some examples of an n-tone composition chart using quasigroup are constructed. In particular, some charts showing a circle of fourths and ﬁfths have been obtained by musical quasigroup. Some examples of ascending, descending, disjunct, and conjunct motions respectively have been described using quasigroups. Also, some examples of contrary, strict contrary, oblique, similar, and parallel motions have been given using quasigroups. The bass, treble, and grand staves have been described by a quasigroup. Examples on motion of a single melody is given having both conjunct and disjunct motions. Also, an example of an oblique motion in which one of its melodies is static while the other moves into conjunct and disjunct motions is demonstrated by a quasigroup. Some examples of a subquasigroup for pitch classes are constructed and veriﬁed with some musical examples. By the concept of a normal subquasigroup, a melodic motion which is disjunct is described to have a sub-melodic motion which is conjunct. It is shown that there are paired melodies which are not in contrary motion to each other but have paired sub-melodies which are in contrary (or strict-contrary) motion.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Quasigroup. Subquasigroup. Normal subquasigroup. n-tone composition chart. Chord inversion. Melodic motion. </em></p>
[Download paper](../wp-content/uploads/2021/06/05-V5n1-Gideon.pdf)

### Neo-Riemannian Graphs Beyond Triads and Seventh Chords
**Ciro Visconti**
<p style="text-align: justify;"><strong>Abstract</strong>: This article develops theoretical concepts that allow us to adapt the graphs used for neo-Riemannian theory to all classes of trichords and tetrachords, beyond triads and seventh chords. To that end, it will be necessary to determine what the main features of these graphs are and the roles that the members of each set class play in them. Each graph is related to a mode of limited transposition, which contains all the pitch classes occurring in the graph. The musical examples extracted from these graphs reveal passages in which the sets are connected by a consistent voice-leading.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Neo-Riemannian theory. Graphs. Voice leading. Contextual inversion. </em></p>
[Download paper](../wp-content/uploads/2021/06/06-V5n1-Visconti.pdf)

### Tonal Progressions Identiﬁcation Through Kripke Semantics
**Francisco Erivelton Fernandes de Aragão**
<p style="text-align: justify;"><strong>Abstract</strong>: The automatic identiﬁcation of tonal chord sequences has already been addressed through several formalisms. We return to this problem for didactic reasons, as we seek a formal solution that lends itself to automatic explanation of the way in which tonal sequences are identiﬁed. There is a search for a correspondence between the formal steps, which lead to the solution, and how a human agent does it to solve the problem him/herself. Given a sequence of chords, the task is to answer whether or not it constitutes a tonal progression, and how and why. It is an interesting problem because its formal solution, once easily automated, can give birth to educational software of real value in the case of young musicians whose access to harmony teachers is scarce or even null. This formalism applied to a large test body allows empirical proof of the fundamental idea that we can describe the tonal sequences by chaining together a minimal collection of basic tonal sequences. Students who do not have access to a harmony teacher will beneﬁt from this harmonic analysis companion.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Tonality identiﬁcation. Modal semantics. Model checking. Automatic harmonic reasoning. </em></p>
[Download paper](../wp-content/uploads/2021/06/07-V5n1-Aragao.pdf)

### A Conceptual Note on Gesture Theory
**Juan Sebastián Arias-Valero and Emilio Lluis-Puebla**
<p style="text-align: justify;"><strong>Abstract</strong>: This paper is a conceptual counterpart of the technical developments of gesture theory. We base all our discussion on Saint-Victor’s deﬁnition of gesture. First, we unfold it to a philosophical reﬂection that could establish a dialogue between semiotic and pre-semiotic approaches to musical gestures, thanks to Peirce’s ideas. Then we explain how the philosophical deﬁnition becomes a mathematical one, and provide reﬂections on important concepts involved in gesture theory, some possible relations to other branches of mathematics and mathematical music theory, and several open and closed questions. We include a non-mathematical discussion related to the environment of this subject and a glossary of specialized terms.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Gestures. Mathematical Music Theory. Category Theory. Geometry. Philosophy. </em></p>
[Download paper](../wp-content/uploads/2021/06/08-V5n1-Valero-Puebla.pdf)

### Modeling, Listening, Analysis, and Computer-Aided Composition
**Silvio Ferraz Mello Filho**
<p style="text-align: justify;"><strong>Abstract</strong>: The main objective of this short paper is to present results and a computational modeling process as a tool to aid musical composition. These results are related to the composition of the piece “Intermezzi and Capriccio” from a Fantasia, an ensemble of piano solo pieces worked from a cross analysis of the ﬁrst Intermezzo of Johannes Brahms’ Four Pieces for Piano Op. 119. In this way, the musical analysis I propose aims to compositional results, which in turn guides, the analysis itself. In this sense, the objective is not that of an analysis and modeling in order to reconstruct an original, but of analysis and modeling that allows it to unfold into new objects.</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Composition. Brahms. Musical modeling. Computer-aided analysis. Max/MSP. zl objects. </em></p>
[Download paper](../wp-content/uploads/2021/06/09-V5n1-Ferraz.pdf)

### Measuring the Amount of Freedom for Compositional Choices in a Textural Perspective
**Daniel Moreira**
<p style="text-align: justify;"><strong>Abstract</strong>: In this paper I discuss the relation between the number of available compositional choices and the complexity in dealing with them in the scope of musical texture. First, I discuss the paradigm of compositional choice in light of the number of variables for a given situation. Then, I introduce the concept of compositional entropy-–a proposal for measuring the amount of freedom that is implied in each compositional choice when selecting a given musical object. This computation depends on the number of available variables provided by the chosen musical object so that the higher the compositional entropy, the more complex is the choosing process as it provides a high number of possibilities to be chosen. This formulation enables the discussion of compositional choices in a view of probability and combinatorial permutations. In the second part of the article, I apply this concept in the textural domain. To do so, I introduce a series of concepts and formulations regarding musical texture to enable such a discussion. Finally, I demonstrate how to measure the compositional entropy of textures, considering both the number of possible textural configurations a composer may manage for a given number of sounding components (exhaustive taxonomy of textures) and how many different ways a given configuration can be realized as music in the score, considering only textural terms (exhaustive taxonomy of realizations).</p>
<p style="text-align: left;"><strong>Keywords</strong>: <em> Compositional entropy. Musical texture. Textural layout. Exhaustive taxonomy. Probability and combinatorial permutations. </em></p>
[Download paper](../wp-content/uploads/2021/06/10-V5n1-Moreira.pdf)